services:
  db:
    image: postgres:15.1
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: serverless
      POSTGRES_USER: tripa
      POSTGRES_PASSWORD: password123
    volumes:
      - ./src/db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5436:5432
